version: '3.7'

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - ./.n8n:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Europe/Istanbul
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1234
